### ISSUE TITLE
Training fails an assertion on start

### ISSUE THREAD

**Issue by jim-22** [guaneec/custom-diffusion-webui#4]
I was able to kick off training with an earlier commit, but after updating to the current one I get the below error when trying to start training. This is with a freshly-created embedding.

```
No saved optimizer exists in checkpoint
  0%|                                                                                         | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\Code\stable-diffusion-webui\extensions\custom-diffusion-webui\cd_modules\custom_diffusion.py", line 207, in _train_embedding
    scaler.step(optimizer)
  File "C:\Users\jim\anaconda3\envs\auto\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 339, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
```

**Comment by guaneec** [comment]
That's odd, I just trained one. Investigating. What was your model's precision? Mine was fp16.

The code up to the exception is almost identical to normal TI. Can you confirm that normal TI training still works properly?
Possibly related: AUTOMATIC1111/stable-diffusion-webui/discussions/5280

**Comment by jim-22** [comment]
Well, I just tried to reproduce it again but it worked fine this time. After looking at the issue you linked, I think it ended up being this strange issue noted in this comment https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/5280#discussioncomment-4293658 where the error seems to be caused by not including [name] in the textual inversion template txt file, because I did indeed happen to use a different txt file with [name] in it when it worked.
