### ISSUE TITLE
Error completing request

### ISSUE THREAD

**Issue by thezveroboy** [guaneec/custom-diffusion-webui#6]
getting error while trying to start training:

Error completing request
Arguments: ('task(owobczqbnqexeys)', 'lancer', '0.0005', 12, 2, 'd:\\datasets\\lancer\\image\\100_lancer\\', '', 1, 'textual_inversion', 512, 512, False, 300, 'disabled', '0.1', False, 0, 'once', 10, 10, 'subject mine.txt', True, True, '1e-5', 0.5, 'photo of lancer', '', 20, 0, 7, -1.0, 768, 512) {}
Traceback (most recent call last):
  File "d:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "d:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "d:\stable-diffusion-webui\extensions\custom-diffusion-webui\cd_modules\custom_diffusion.py", line 12, in train_embedding
    embedding, filename = _train_embedding(*args)
  File "d:\stable-diffusion-webui\extensions\custom-diffusion-webui\cd_modules\custom_diffusion.py", line 37, in _train_embedding
    os.makedirs(shared.cmd_opts.deltas_dir, exist_ok=True)
AttributeError: 'Namespace' object has no attribute 'deltas_dir'

**Comment by guaneec** [comment]
Cannot reproduce.
Can you provide the commit hash and the command line arguments of the Web UI?

**Comment by thezveroboy** [comment]
sure
Commit hash: 127bfb6c415a5a11deea4451b9a7e5ca6ddd48d7
set COMMANDLINE_ARGS=--xformers

**Comment by guaneec** [comment]
Tried the same and still can't reproduce on the latest version of the extension.
Can you confirm the contents of `extensions\custom-diffusion-webui\preload.py` is properly loaded by adding something like `print("PRELOAD LOADED")` to the `preload()` function and relaunching the Web UI?

**Comment by thezveroboy** [comment]
after your question about commit i've used i had update my auto1111 and all work perfectly now. so problem was in old version. thank you for your response and help!
